handlers=java.util.logging.ConsoleHandler

.level=INFO
io.github.elektrofuzzis.ftswarm_clients.kotlin.transport.Serial.level=FINEST

java.util.logging.ConsoleHandler.level=ALL
java.util.logging.ConsoleHandler.formatter=ShortFormatter
